--- #YAML:1.0
name:                   Games-Trackword
version:                1.05
abstract:               A collection of modules for accessing phrasebooks from various data sources.
author:
  - Barbie <barbie@cpan.org>

license:                perl
distribution_type:      module
installdirs:            site

requires:
  Test::More:           0.47
recommends:
  Test::More:           0.47
  Test::Pod:            1.00
  Test::Pod::Coverage:  0.08
  Test::YAML::Valid:    0
build_requires:
  Test::More:           0.47

provides:
  Games::Trackword:
    file:     lib/Games/Trackword.pm
    version:  1.05
no_index:
  directory:
    - t
    - examples

meta-spec:
 version:     1.3
 url:         http://module-build.sourceforge.net/META-spec-v1.3.html
generated_by: Hand 1.0
