--- #YAML:1.0
name:                   Games-Trackword
version:                1.09
abstract:               A module to help find words on a Trackword grid
author:
  - Barbie <barbie@cpan.org>

license:                artistic_2
distribution_type:      module
installdirs:            site

requires:
  perl:                           5.006
recommends:
  Test::CPAN::Meta:               0
  Test::CPAN::Meta::JSON:         0
  Test::Pod:                      1.00
  Test::Pod::Coverage:            0.08
build_requires:
  IO::File:                       0
  Test::More:                     0.70

provides:
  Games::Trackword:
    file:     lib/Games/Trackword.pm
    version:  1.09
no_index:
  directory:
    - t
    - examples

resources:
  license:    http://www.perlfoundation.org/artistic_license_2_0
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Games-Trackword
  repository: http://github.com/barbie/games-trackword

meta-spec:
   version:   1.4
   url:       http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: The Hand of Barbie 1.0
